name: deploy

on:
  push:
    branches:
      - development
      - staging
      - production

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, tag, and push image to container registry
        run: |
          docker buildx build \
            --platform linux/arm64 --push -t "registry.digitalocean.com/crowdcast-do-registry/supabase-realtime:$STAGE" \
            .
        env:
          STAGE: ${{ github.ref_name }}